# Generated by Django 5.2 on 2026-05-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfiltendero",
            name="proveedor",
            field=models.CharField(
                choices=[
                    ("claude", "Claude (Anthropic)"),
                    ("gemini", "Gemini (Google)"),
                    ("groq", "Groq"),
                    ("ollama", "Ollama (Local)"),
                ],
                default="gemini",
                max_length=20,
            ),
        ),
    ]
