# Generated by Django 5.2 on 2026-05-18 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GraficaDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[("default", "Por defecto"), ("ia", "Generada por IA")],
                        default="default",
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("tipo", models.CharField(default="bar", max_length=20)),
                ("query_key", models.CharField(blank=True, max_length=100, null=True)),
                ("query_params", models.JSONField(default=dict)),
                ("labels", models.JSONField(blank=True, null=True)),
                ("datos", models.JSONField(blank=True, null=True)),
                ("orden", models.IntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graficas_dashboard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "creado_en"],
            },
        ),
        migrations.CreateModel(
            name="VistaDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("graficas", models.JSONField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vistas_dashboard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
