# Generated by Django 5.2 on 2026-05-17 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación",
                "verbose_name_plural": "Conversaciones",
                "ordering": ["-creada_en"],
            },
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("usuario", "Usuario"), ("asistente", "Asistente")],
                        max_length=20,
                    ),
                ),
                ("contenido", models.TextField()),
                ("tipo_respuesta", models.CharField(default="texto", max_length=20)),
                ("datos_grafica", models.JSONField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="inteligencia.conversacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "ordering": ["creado_en"],
            },
        ),
    ]
